/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 02 04:44:18 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.ComboLeg;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ComboLeg_ESTest extends ComboLeg_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      comboLeg0.m_action = "uy{k}jEsM><e}";
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_openClose);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
      assertFalse(boolean0);
      assertEquals(0, comboLeg1.m_conId);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertTrue(comboLeg1.equals((Object)comboLeg0));
      
      comboLeg1.m_exchange = "kCN>D@8";
      boolean boolean0 = comboLeg1.equals(comboLeg0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      comboLeg0.m_designatedLocation = "B";
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_conId);
      assertFalse(boolean0);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      
      comboLeg1.m_shortSaleSlot = (-2655);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(0, 0, "8ZPf\"*,esjwu", "8ZPf\"*,esjwu", 0);
      ComboLeg comboLeg1 = new ComboLeg(0, 0, "", "8ZPf\"*,esjwu", 1);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg0.m_openClose);
      assertEquals(1, comboLeg1.m_openClose);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      assertEquals(0, comboLeg0.m_openClose);
      
      comboLeg0.m_openClose = 3212;
      ComboLeg comboLeg1 = new ComboLeg(0, 0, "", "", 0);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg(0, 2, (String) null, "", 0);
      boolean boolean0 = comboLeg1.equals(comboLeg0);
      assertEquals(2, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertFalse(boolean0);
      assertFalse(comboLeg0.equals((Object)comboLeg1));
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_openClose);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      assertEquals(0, comboLeg0.m_conId);
      
      ComboLeg comboLeg1 = new ComboLeg(0, 0, (String) null, (String) null, 0, 1, "");
      comboLeg0.m_conId = 1;
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(2, 2, "", "<brZ", 2);
      ComboLeg comboLeg1 = new ComboLeg(2676, 2682, "", "", 0);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertEquals(2682, comboLeg1.m_ratio);
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      assertEquals(2676, comboLeg1.m_conId);
      assertFalse(boolean0);
      assertEquals(2, comboLeg0.m_openClose);
      assertEquals(0, comboLeg1.m_openClose);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg0);
      assertEquals(0, comboLeg0.m_conId);
      assertTrue(boolean0);
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      assertEquals(0, comboLeg0.m_ratio);
      assertEquals(0, comboLeg0.m_openClose);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertTrue(comboLeg1.equals((Object)comboLeg0));
      
      comboLeg1.m_designatedLocation = "b1p0O,&j:_PN?FfXoz";
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      assertTrue(comboLeg1.equals((Object)comboLeg0));
      
      comboLeg1.m_exchange = "kCN>D@8";
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(comboLeg1.equals((Object)comboLeg0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertTrue(boolean0);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(0, 0, "O}!kf<mZ^} Yj*ys*", "O}!kf<mZ^} Yj*ys*", 0);
      ComboLeg comboLeg1 = new ComboLeg();
      boolean boolean0 = comboLeg1.equals(comboLeg0);
      assertEquals(0, comboLeg1.m_conId);
      assertEquals(0, comboLeg1.m_openClose);
      assertEquals(0, comboLeg1.m_ratio);
      assertEquals(0, comboLeg1.m_shortSaleSlot);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(0, 0, "O}!kf<mZ^} Yj*ys*", "O}!kf<mZ^} Yj*ys*", (-886));
      ComboLeg comboLeg1 = new ComboLeg();
      assertEquals(0, comboLeg1.m_ratio);
      
      comboLeg1.m_ratio = 2;
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(0, 0, "O}!kf<mZ^} Yj*ys*", "O}!kf<mZ^} Yj*ys*", (-886));
      boolean boolean0 = comboLeg0.equals((Object) null);
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      assertEquals(0, comboLeg0.m_ratio);
      assertEquals((-886), comboLeg0.m_openClose);
      assertFalse(boolean0);
      assertEquals(0, comboLeg0.m_conId);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg(0, 0, "O}!kf<mZ^} Yj*ys*", "O}!kf<mZ^} Yj*ys*", (-886));
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        comboLeg0.equals(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.ib.client.ComboLeg
         //
         verifyException("com.ib.client.ComboLeg", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ComboLeg comboLeg0 = new ComboLeg();
      assertEquals(0, comboLeg0.m_shortSaleSlot);
      
      ComboLeg comboLeg1 = new ComboLeg();
      comboLeg0.m_shortSaleSlot = (-357);
      boolean boolean0 = comboLeg0.equals(comboLeg1);
      assertFalse(boolean0);
  }
}
