/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 02 04:37:59 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.ContractDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContractDetails_ESTest extends ContractDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContractDetails contractDetails0 = new ContractDetails();
      ContractDetails contractDetails1 = new ContractDetails(contractDetails0.m_summary, "com.ib.client.UnderComp", (String) null, 0.0, "tfLYMpnie6v-/ H<=", "com.ib.client.Contract", 0, (String) null, (String) null, "", ")*lvC<fvnf8XQ}F", (String) null, (String) null, "com.ib.client.ContractDetails", ")*lvC<fvnf8XQ}F");
      assertEquals(0.0, contractDetails0.m_minTick, 0.01);
      assertFalse(contractDetails1.m_putable);
      assertFalse(contractDetails0.m_putable);
      assertEquals(0.0, contractDetails0.m_coupon, 0.01);
      assertFalse(contractDetails0.m_callable);
  }
}
