/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 28 03:11:21 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.ContractDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ContractDetails_ESTest extends ContractDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ContractDetails contractDetails0 = new ContractDetails();
      ContractDetails contractDetails1 = new ContractDetails(contractDetails0.m_summary, "5&OJr@!WGua>J:K5*`", "5&OJr@!WGua>J:K5*`", (-256.6), (String) null, (String) null, 1662, (String) null, "", (String) null, "", "", (String) null, (String) null, (String) null);
      assertEquals(0.0, contractDetails0.m_coupon, 0.01);
      assertEquals((-256.6), contractDetails1.m_minTick, 0.01);
      assertEquals(0.0, contractDetails0.m_minTick, 0.01);
      assertEquals(1662, contractDetails1.m_underConId);
      assertFalse(contractDetails1.m_convertible);
      assertEquals(0, contractDetails0.m_underConId);
      assertEquals(0.0, contractDetails1.m_coupon, 0.01);
  }
}
