/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 28 03:10:24 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.EClientErrors;
import com.ib.client.EException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EException_ESTest extends EException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair((-855), "Cancel Scanner Subscription Sending Error - ");
      EException eException0 = new EException((-855), eClientErrors_CodeMsgPair0);
      String string0 = eException0.getMessage();
      assertEquals("Cancel Scanner Subscription Sending Error -  [id = -855, errorCode = -855]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair((-855), "Cancel Scanner Subscription Sending Error - ");
      EException eException0 = new EException((-855), eClientErrors_CodeMsgPair0);
      int int0 = eException0.getErrorCode();
      assertEquals((-855), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EException eException0 = new EException("O");
      assertEquals((-1), EException.NO_VALID_CODE);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EClientErrors.CodeMsgPair eClientErrors_CodeMsgPair0 = new EClientErrors.CodeMsgPair((-855), "Cancel Scanner Subscription Sending Error - ");
      EException eException0 = new EException((-855), eClientErrors_CodeMsgPair0);
      int int0 = eException0.getId();
      assertEquals((-855), int0);
  }
}
