/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 28 03:18:32 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.Execution;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Execution_ESTest extends Execution_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Execution execution0 = new Execution(0, 0, "9^%:PH9", "9^%:PH9", (String) null, "", "", 0, 0, (-1398), (-1398), 2783, 0);
      Execution execution1 = new Execution();
      boolean boolean0 = execution0.equals(execution1);
      assertFalse(boolean0);
      assertEquals(0.0, execution1.m_price, 0.01);
      assertEquals(0, execution1.m_shares);
      assertEquals(0, execution1.m_orderId);
      assertEquals(0, execution0.m_orderId);
      assertEquals(0.0, execution1.m_avgPrice, 0.01);
      assertEquals(0, execution0.m_clientId);
      assertEquals((-1398), execution0.m_permId);
      assertEquals(0, execution1.m_clientId);
      assertEquals((-1398), execution0.m_liquidation);
      assertEquals(0, execution0.m_shares);
      assertEquals(2783, execution0.m_cumQty);
      assertEquals(0, execution1.m_cumQty);
      assertEquals(0, execution1.m_permId);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Execution execution0 = new Execution(0, 0, "9^%:PH9", "9^%:PH9", (String) null, "", "", 0, 0, (-1398), (-1398), 2783, 0);
      boolean boolean0 = execution0.equals((Object) null);
      assertEquals(0.0, execution0.m_price, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, execution0.m_avgPrice, 0.01);
      assertEquals(0, execution0.m_orderId);
      assertEquals(2783, execution0.m_cumQty);
      assertEquals(0, execution0.m_shares);
      assertEquals(0, execution0.m_clientId);
      assertEquals((-1398), execution0.m_liquidation);
      assertEquals((-1398), execution0.m_permId);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Execution execution0 = new Execution(0, 0, "9^%:PH9", "9^%:PH9", (String) null, "", "", 0, 0, (-1398), (-1398), 2783, 0);
      boolean boolean0 = execution0.equals(execution0);
      assertEquals(0.0, execution0.m_price, 0.01);
      assertEquals((-1398), execution0.m_liquidation);
      assertEquals((-1398), execution0.m_permId);
      assertEquals(2783, execution0.m_cumQty);
      assertEquals(0, execution0.m_shares);
      assertTrue(boolean0);
      assertEquals(0, execution0.m_clientId);
      assertEquals(0.0, execution0.m_avgPrice, 0.01);
      assertEquals(0, execution0.m_orderId);
  }
}
