/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 28 03:11:35 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.OrderState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrderState_ESTest extends OrderState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertTrue(orderState1.equals((Object)orderState0));
      
      orderState0.m_commissionCurrency = "wq_98";
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      orderState0.m_equityWithLoan = "f /f";
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState("Q", (String) null, "Q", (String) null, 0.0, 0.0, 0.0, (String) null, (String) null);
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_commission, 0.01);
      assertFalse(orderState1.equals((Object)orderState0));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "]t]G(Dt!M+G0=\"", "@=f#;SK", "", 0.0, 0.0, 0.0, "", "");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertTrue(orderState1.equals((Object)orderState0));
      
      orderState1.m_status = "|vN>M8";
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      
      orderState1.m_maxCommission = (-2134.63414381938);
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState("", (String) null, "", (String) null, 0.0, 1.0, (-914.3799), (String) null, "hpn8*Bk97uGCcOJXo#");
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
      assertEquals(1.0, orderState1.m_minCommission, 0.01);
      assertEquals((-914.3799), orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertTrue(boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertEquals(0.0, orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      OrderState orderState0 = new OrderState("f /f", "", "", "", 2648.470116603498, 2648.470116603498, 2648.470116603498, "f /f", "PX8]");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
      assertEquals(2648.470116603498, orderState0.m_commission, 0.01);
      assertEquals(2648.470116603498, orderState0.m_minCommission, 0.01);
      assertEquals(2648.470116603498, orderState0.m_maxCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) null);
      assertEquals(0.0, orderState0.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01);
      assertEquals(0.0, orderState0.m_commission, 0.01);
  }
}
