/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 02 04:38:28 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.OrderState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OrderState_ESTest extends OrderState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertTrue(orderState1.equals((Object)orderState0));
      
      orderState1.m_commissionCurrency = "`igmt/%Yhk3";
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState((String) null, (String) null, (String) null, "b9HuF7{&8%Ad]&T}", 0.0, 0.0, 0.0, "[o0.Y", (String) null);
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      orderState0.m_maintMargin = "}0{$D[.1G(lib<p";
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState("2BWn", "c// FhQ", "J rGv<<>6*", "", 0.0, 0.0, 0.0, "{IRY", (String) null);
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertTrue(orderState1.equals((Object)orderState0));
      
      orderState0.m_status = "com.ib.client.OrderState";
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", "", "", 0.0, 0.0, 0.0, "(e[5`3F1z$B|", "");
      OrderState orderState1 = new OrderState("8q", (String) null, "", "8q", 0.0, 0.0, 90.32849704211002, "(e[5`3F1z$B|", "");
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
      assertEquals(90.32849704211002, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_commission, 0.01);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      
      orderState1.m_minCommission = 336.0048149167;
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", (String) null, "M{vcX2cwr<(.$4j", (-2689.6055588818463), 0.0, 0.0, "IlW)oR@T|heW~", "");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals((-2689.6055588818463), orderState0.m_commission, 0.01);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01);
      assertEquals(0.0, orderState0.m_minCommission, 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", "", "", 1.0, 1.0, 0.0, "", "Q/EZ;");
      OrderState orderState1 = new OrderState("", "", "", "", 1.0, 1.0, 0.0, "", "");
      boolean boolean0 = orderState0.equals(orderState1);
      assertTrue(boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(1.0, orderState1.m_minCommission, 0.01);
      assertEquals(1.0, orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      
      orderState1.m_minCommission = 336.0048149167;
      boolean boolean0 = orderState1.equals(orderState0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      OrderState orderState0 = new OrderState((String) null, (String) null, "", (String) null, 1.0, 1.0, (-1682.001), "vBLUg", "*");
      boolean boolean0 = orderState0.equals(orderState0);
      assertEquals(1.0, orderState0.m_minCommission, 0.01);
      assertTrue(boolean0);
      assertEquals((-1682.001), orderState0.m_maxCommission, 0.01);
      assertEquals(1.0, orderState0.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OrderState orderState0 = new OrderState("fUR[aq+]:)Gq", "", (String) null, "", 0.0, 0.0, 0.0, "#F~Y", "fUR[aq+]:)Gq");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      OrderState orderState0 = new OrderState("com.ib.client.OrderState", "c&myq/E`Aplb 'Ndc", "com.ib.client.OrderState", "qPN2-]I7X}.BCJ", 1963.697775527955, 1963.697775527955, 1963.697775527955, "c&myq/E`Aplb 'Ndc", "qPN2-]I7X}.BCJ");
      OrderState orderState1 = new OrderState("qPN2-]I7X}.BCJ", "c&myq/E`Aplb 'Ndc", "com.ib.client.OrderState", "", 1963.697775527955, 1963.697775527955, 1963.697775527955, "c&myq/E`Aplb 'Ndc", "cxV/gZ");
      assertFalse(orderState1.equals((Object)orderState0));
      
      orderState1.m_maintMargin = "cxV/gZ";
      orderState0.equals(orderState1);
      assertEquals(1963.697775527955, orderState1.m_commission, 0.01);
      assertEquals(1963.697775527955, orderState1.m_maxCommission, 0.01);
      assertEquals(1963.697775527955, orderState1.m_minCommission, 0.01);
      assertEquals(1963.697775527955, orderState0.m_minCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      OrderState orderState0 = new OrderState("com.ib.client.OrderState", "com.ib.client.OrderState", "", "", 0.0, 0.0, 0.0, "Hxm95=:`", "lQLVb>kllz>0H(.v_#");
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals(0.0, orderState1.m_commission, 0.01);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      assertTrue(orderState1.equals((Object)orderState0));
      
      orderState0.m_status = "com.ib.client.OrderState";
      boolean boolean0 = orderState1.equals(orderState0);
      assertFalse(orderState1.equals((Object)orderState0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState("", "e", (String) null, "~q%5F\"3.?nq5(!Bo~V", 0.0, 0.0, (-113.205156891854), (String) null, "~q%5F\"3.?nq5(!Bo~V");
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals((-113.205156891854), orderState1.m_maxCommission, 0.01);
      assertEquals(0.0, orderState1.m_commission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState((String) null, (String) null, "~q%5F\"3.?nq5(!Bo~V", "5n4xSl^}=dc|2F,nB", (-1.0), 0.0, 1.0, (String) null, "aT;)S\"");
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals(1.0, orderState1.m_maxCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertEquals((-1.0), orderState1.m_commission, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      boolean boolean0 = orderState0.equals((Object) null);
      assertEquals(0.0, orderState0.m_commission, 0.01);
      assertEquals(0.0, orderState0.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState0.m_maxCommission, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      OrderState orderState0 = new OrderState();
      // Undeclared exception!
      try { 
        orderState0.equals("");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.ib.client.OrderState
         //
         verifyException("com.ib.client.OrderState", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      OrderState orderState0 = new OrderState("", "", "", "C#UdytXT", 0.0, 0.0, 0.0, "", (String) null);
      OrderState orderState1 = new OrderState();
      boolean boolean0 = orderState0.equals(orderState1);
      assertEquals(0.0, orderState1.m_minCommission, 0.01);
      assertFalse(boolean0);
      assertEquals(0.0, orderState1.m_maxCommission, 0.01);
      assertFalse(orderState1.equals((Object)orderState0));
      assertEquals(0.0, orderState1.m_commission, 0.01);
  }
}
