/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 28 03:10:33 GMT 2018
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ib.client.UnderComp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnderComp_ESTest extends UnderComp_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      UnderComp underComp1 = new UnderComp();
      boolean boolean0 = underComp0.equals(underComp1);
      assertEquals(0.0, underComp1.m_price, 0.01);
      assertTrue(boolean0);
      assertEquals(0.0, underComp1.m_delta, 0.01);
      assertEquals(0, underComp1.m_conId);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      UnderComp underComp1 = new UnderComp();
      assertEquals(0.0, underComp1.m_delta, 0.01);
      
      underComp1.m_delta = (-290.2708821164);
      boolean boolean0 = underComp1.equals(underComp0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      assertEquals(0, underComp0.m_conId);
      
      underComp0.m_conId = 2815;
      UnderComp underComp1 = new UnderComp();
      boolean boolean0 = underComp1.equals(underComp0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      Object object0 = new Object();
      boolean boolean0 = underComp0.equals(object0);
      assertFalse(boolean0);
      assertEquals(0.0, underComp0.m_price, 0.01);
      assertEquals(0, underComp0.m_conId);
      assertEquals(0.0, underComp0.m_delta, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      boolean boolean0 = underComp0.equals((Object) null);
      assertEquals(0.0, underComp0.m_price, 0.01);
      assertEquals(0.0, underComp0.m_delta, 0.01);
      assertFalse(boolean0);
      assertEquals(0, underComp0.m_conId);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UnderComp underComp0 = new UnderComp();
      assertEquals(0.0, underComp0.m_price, 0.01);
      
      UnderComp underComp1 = new UnderComp();
      underComp0.m_price = (-290.2708821164);
      boolean boolean0 = underComp0.equals(underComp1);
      assertFalse(boolean0);
  }
}
